# Plan de cuentas PCGA Chile estándar para PYME
# (codigo, nombre, tipo, naturaleza, es_titulo, nivel)

PLAN_CUENTAS_CHILE = [
    # ── ACTIVOS ──────────────────────────────────────────────────────────────
    ('1',      'ACTIVOS',                               'ACTIVO',    'DEUDORA',   True,  1),
    ('1.1',    'Activo Circulante',                     'ACTIVO',    'DEUDORA',   True,  2),
    ('1.1.01', 'Caja',                                  'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.02', 'Banco',                                 'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.03', 'Clientes',                              'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.04', 'Documentos por Cobrar',                 'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.05', 'IVA Crédito Fiscal',                    'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.06', 'PPM',                                   'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.07', 'Anticipos a Proveedores',               'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.08', 'Existencias',                           'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.09', 'Inversiones en Fondos Mutuos',          'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.10', 'Préstamos a Terceros por Cobrar',        'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.11', 'Préstamos a Emp. Relacionadas',         'ACTIVO',    'DEUDORA',   False, 3),
    ('1.1.12', 'Otros Activos Circulantes',             'ACTIVO',    'DEUDORA',   False, 3),
    ('1.2',    'Activo Fijo',                           'ACTIVO',    'DEUDORA',   True,  2),
    ('1.2.01', 'Terrenos',                              'ACTIVO',    'DEUDORA',   False, 3),
    ('1.2.02', 'Construcciones y Obras',                'ACTIVO',    'DEUDORA',   False, 3),
    ('1.2.03', 'Maquinarias y Equipos',                 'ACTIVO',    'DEUDORA',   False, 3),
    ('1.2.04', 'Vehículos',                             'ACTIVO',    'DEUDORA',   False, 3),
    ('1.2.05', 'Muebles y Enseres',                     'ACTIVO',    'DEUDORA',   False, 3),
    ('1.2.06', 'Equipos Computacionales',               'ACTIVO',    'DEUDORA',   False, 3),
    ('1.2.07', 'Dep. Acum. Construcciones',             'ACTIVO',    'ACREEDORA', False, 3),
    ('1.2.08', 'Dep. Acum. Maquinarias',                'ACTIVO',    'ACREEDORA', False, 3),
    ('1.2.09', 'Dep. Acum. Vehículos',                  'ACTIVO',    'ACREEDORA', False, 3),
    ('1.2.10', 'Dep. Acum. Muebles',                    'ACTIVO',    'ACREEDORA', False, 3),
    ('1.2.11', 'Dep. Acum. Equipos Comp.',              'ACTIVO',    'ACREEDORA', False, 3),
    ('1.3',    'Otros Activos',                         'ACTIVO',    'DEUDORA',   True,  2),
    ('1.3.01', 'Inversiones Largo Plazo',               'ACTIVO',    'DEUDORA',   False, 3),
    ('1.3.02', 'Intangibles',                           'ACTIVO',    'DEUDORA',   False, 3),
    ('1.3.03', 'Otros Activos',                         'ACTIVO',    'DEUDORA',   False, 3),

    # ── PASIVOS ───────────────────────────────────────────────────────────────
    ('2',      'PASIVOS',                               'PASIVO',    'ACREEDORA', True,  1),
    ('2.1',    'Pasivo Circulante',                     'PASIVO',    'ACREEDORA', True,  2),
    ('2.1.01', 'Proveedores',                           'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.02', 'Documentos por Pagar',                  'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.03', 'IVA Débito Fiscal',                     'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.04', 'Retención Honorarios por Pagar',        'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.05', 'Remuneraciones por Pagar',              'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.06', 'Cotizaciones Previsionales por Pagar',  'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.07', 'Impuesto a la Renta por Pagar',         'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.08', 'PPM por Enterar',                       'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.09', 'Anticipos de Clientes',                 'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.10', 'Préstamos Bancarios',                   'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.11', 'Préstamos de Terceros',                 'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.12', 'Préstamos Emp. Relacionadas',           'PASIVO',    'ACREEDORA', False, 3),
    ('2.1.13', 'Otros Pasivos Circulantes',             'PASIVO',    'ACREEDORA', False, 3),
    ('2.2',    'Pasivo Largo Plazo',                    'PASIVO',    'ACREEDORA', True,  2),
    ('2.2.01', 'Préstamos Bancarios LP',                'PASIVO',    'ACREEDORA', False, 3),
    ('2.2.02', 'Préstamos de Terceros LP',              'PASIVO',    'ACREEDORA', False, 3),
    ('2.2.03', 'Préstamos Emp. Relacionadas LP',        'PASIVO',    'ACREEDORA', False, 3),
    ('2.2.04', 'Otros Pasivos LP',                      'PASIVO',    'ACREEDORA', False, 3),

    # ── PATRIMONIO ────────────────────────────────────────────────────────────
    ('3',      'PATRIMONIO',                            'PATRIMONIO','ACREEDORA', True,  1),
    ('3.1',    'Patrimonio Neto',                       'PATRIMONIO','ACREEDORA', True,  2),
    ('3.1.01', 'Capital Pagado',                        'PATRIMONIO','ACREEDORA', False, 3),
    ('3.1.02', 'Otras Reservas',                        'PATRIMONIO','ACREEDORA', False, 3),
    ('3.1.03', 'Utilidades Acumuladas',                 'PATRIMONIO','ACREEDORA', False, 3),
    ('3.1.04', 'Pérdidas Acumuladas',                   'PATRIMONIO','DEUDORA',   False, 3),
    ('3.1.05', 'Resultado del Ejercicio',               'PATRIMONIO','ACREEDORA', False, 3),
    ('3.1.06', 'Retiros del Ejercicio',                 'PATRIMONIO','DEUDORA',   False, 3),

    # ── INGRESOS ──────────────────────────────────────────────────────────────
    ('4',      'INGRESOS',                              'INGRESO',   'ACREEDORA', True,  1),
    ('4.1',    'Ingresos de Explotación',               'INGRESO',   'ACREEDORA', True,  2),
    ('4.1.01', 'Ventas Afectas',                        'INGRESO',   'ACREEDORA', False, 3),
    ('4.1.02', 'Ventas Exentas',                        'INGRESO',   'ACREEDORA', False, 3),
    ('4.1.03', 'Ventas de Exportación',                 'INGRESO',   'ACREEDORA', False, 3),
    ('4.1.04', 'Servicios Afectos',                     'INGRESO',   'ACREEDORA', False, 3),
    ('4.1.05', 'Servicios Exentos',                     'INGRESO',   'ACREEDORA', False, 3),
    ('4.2',    'Ingresos Fuera de Explotación',         'INGRESO',   'ACREEDORA', True,  2),
    ('4.2.01', 'Ingresos Financieros',                  'INGRESO',   'ACREEDORA', False, 3),
    ('4.2.02', 'Utilidad en Venta de Activos',          'INGRESO',   'ACREEDORA', False, 3),
    ('4.2.03', 'Otros Ingresos',                        'INGRESO',   'ACREEDORA', False, 3),

    # ── GASTOS ────────────────────────────────────────────────────────────────
    ('5',      'GASTOS',                                'GASTO',     'DEUDORA',   True,  1),
    ('5.1',    'Costo de Ventas',                       'GASTO',     'DEUDORA',   True,  2),
    ('5.1.01', 'Costo de Mercaderías Vendidas',         'GASTO',     'DEUDORA',   False, 3),
    ('5.2',    'Gastos de Administración y Ventas',     'GASTO',     'DEUDORA',   True,  2),
    ('5.2.01', 'Remuneraciones y Sueldos',              'GASTO',     'DEUDORA',   False, 3),
    ('5.2.02', 'Honorarios',                            'GASTO',     'DEUDORA',   False, 3),
    ('5.2.03', 'Arriendo',                              'GASTO',     'DEUDORA',   False, 3),
    ('5.2.04', 'Agua, Luz y Gas',                       'GASTO',     'DEUDORA',   False, 3),
    ('5.2.05', 'Teléfono e Internet',                   'GASTO',     'DEUDORA',   False, 3),
    ('5.2.06', 'Materiales y Suministros',              'GASTO',     'DEUDORA',   False, 3),
    ('5.2.07', 'Mantención y Reparaciones',             'GASTO',     'DEUDORA',   False, 3),
    ('5.2.08', 'Seguros',                               'GASTO',     'DEUDORA',   False, 3),
    ('5.2.09', 'Transporte y Movilización',             'GASTO',     'DEUDORA',   False, 3),
    ('5.2.10', 'Publicidad y Marketing',                'GASTO',     'DEUDORA',   False, 3),
    ('5.2.11', 'Asesorías y Consultorías',              'GASTO',     'DEUDORA',   False, 3),
    ('5.2.12', 'Gastos Bancarios e Intereses',          'GASTO',     'DEUDORA',   False, 3),
    ('5.2.13', 'Comisiones',                            'GASTO',     'DEUDORA',   False, 3),
    ('5.2.14', 'Depreciación del Ejercicio',            'GASTO',     'DEUDORA',   False, 3),
    ('5.2.15', 'Gastos de Representación',              'GASTO',     'DEUDORA',   False, 3),
    ('5.2.16', 'Impuestos y Contribuciones',            'GASTO',     'DEUDORA',   False, 3),
    ('5.2.17', 'Otros Gastos',                          'GASTO',     'DEUDORA',   False, 3),
    ('5.3',    'Gastos Fuera de Explotación',           'GASTO',     'DEUDORA',   True,  2),
    ('5.3.01', 'Pérdida en Venta de Activos',           'GASTO',     'DEUDORA',   False, 3),
    ('5.3.02', 'Otros Gastos No Operacionales',         'GASTO',     'DEUDORA',   False, 3),
]
